export const ScheduleData = [
  {
    id: 1,
    name: "Larissa Silva Gonçalves",
    planned: 10,
    accomplished: 10,
    lastUpdate: "08:10h 10/10/2010",
  },
  {
    id: 2,
    name: "Lucas Silva Santos",
    planned: 10,
    accomplished: 10,
    lastUpdate: "08:10h 10/10/2010",
  },
  {
    id: 3,
    name: "Raissa Oliveira Araujo ",
    planned: 10,
    accomplished: 10,
    lastUpdate: "08:10h",
  },
  {
    id: 4,
    name: "Leila Dias Costa",
    planned: 8,
    accomplished: 8,
    lastUpdate: "08:10h",
  },
  {
    id: 5,
    name: "Vitória Sousa Cavalcanti",
    planned: "-",
    accomplished: "-",
    lastUpdate: "08:10h",
  },
  {
    id: 6,
    name: "Emily Araujo Oliveira",
    planned: 4,
    accomplished: 4,
    lastUpdate: "08:10h",
  },
  {
    id: 7,
    name: "Nicolas Pereira Sousa",
    planned: 2,
    accomplished: 2,
    lastUpdate: "08:10h 10/10/2010",
  },
  {
    id: 8,
    name: "Laura Castro Gomes",
    planned: 2,
    accomplished: 2,
    lastUpdate: "08:10h",
  },
];
